spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${AUTH_DB_USER:auth_user}
    password: ${AUTH_DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8081}
