spring:
  application:
    name: course-service
  datasource:
    url: ${COURSE_DB_URL:jdbc:postgresql://localhost:5432/coursedb}
    username: ${COURSE_DB_USER:course_user}
    password: ${COURSE_DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8082}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
